on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: ros:noetic-ros-core-focal
    name: rosbuild
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: gen_build
        run: ./.ci/generate_build.sh

      - name: check format
        run: ./.ci/check_format.sh
